server:
  port: 3333
spring:
  application:
    name: service-hi
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    home-page-url: /home
##实例名命名默认规则中加入了instance-id，可以在这里加上
#  instance:
#    instance-id: ${spring.application.name}:${random.int}
