eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 5555
spring:
  application:
    name: service-zuul

# serviceId区分大小写，要和注册到eureka上的一样
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: SERVICE-RIBBON
    api-b:
      path: /api-b/**
      serviceId: SERVICE-FEIGN
