
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/weiguangshuai/springcloud.git
          search-paths: respo
          username:
          password:
      label: master
server:
  port: 6666

