spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/weiguangshuai/springcloud.git
          search-paths: respo
          username: weiguangshuai
          password: weishuai19961023
      label: master
server:
  port: 1116
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
